### PR TITLE
Fix uvc header definition && Update video_static_mjpeg_template

### PR DESCRIPTION
**Pull request by yjun123**
RT

### CODE REVIEW

**Comment by sakumisu** [comment]
Good boy, thanks, for endpoint, we have USB_ENDPOINT_DESCRIPTOR_INIT, you can use it, i am too lazy.

**Comment by sakumisu** [comment]
Also can you help to modify other template, like video yuyv and h264?

**Comment by yjun123** [comment]
> Also can you help to modify other template, like video yuyv and h264?

I'd be happy to.

**Comment by sakumisu** [comment]
Any update?

**Pull request closed without merging**
